version: '3.9'

services:
  api:
    container_name: api_mycash
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
      
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    
  db:
    container_name: db_mycash
    image: postgres:14
    ports: 
      - 5431:5432
    env_file:
      - .env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: 
    driver: local